### ISSUE TITLE
Generator view update button

### ISSUE THREAD

**Issue by bbvothuy** [bbvothuy/oemasia#114]
- [x] Update currency table 
[update_rates_php.txt](https://github.com/bbvothuy/oemasia/files/2475495/update_rates_php.txt)

- [x] Update generator view

**Comment by cuonghuynh** [comment]
![2018-10-14_02-46-01](https://user-images.githubusercontent.com/3349033/46909374-677cb600-cf5b-11e8-9d34-0f6d1d1004f7.png)
