### ISSUE TITLE
Update columns on generators list

### ISSUE THREAD

**Issue by cuonghuynh** [bbvothuy/oemasia#53]
- [ ] Remove Voltage
- [ ] Remove Frequency
- [ ] Add Alternator heading
- [ ] Add 3 sub-columns to Engine and Alternator
- [ ] Remove VND currency and move to heading

![2018-04-25_14-56-24](https://user-images.githubusercontent.com/3349033/39233000-57b660fc-4899-11e8-9b53-40eb867383e0.png)

**Comment by bbvothuy** [comment]
#34 closed
