### ISSUE TITLE
Genset filter search 

### ISSUE THREAD

**Issue by bbvothuy** [bbvothuy/oemasia#62]
![image](https://user-images.githubusercontent.com/5876231/40760227-f7b46a9e-64bf-11e8-8222-6a2f9d074056.png)

**Comment by cuonghuynh** [comment]
Genset Type (genset_type): Categories > Genset_type > Level 1
Canopy (canopy):
- Võ trần
- Võ cách âm
Origin (genset_origin) : Categories > Origins > Level 1
DeliveryTime (delivery_time): 
- < 20 days
- < 45 days
- < 90 days
Engine Maker (engine_manu): Manufacturers
Origin (engine_origin): Categories > Origins > Level 1
Alternator Maker: Manufacturers
Origin (alternator_origin): Categories > Origins > Level 1
