### ISSUE TITLE
Our suppliers

### ISSUE THREAD

**Issue by bbvothuy** [bbvothuy/oemasia#67]
![image](https://user-images.githubusercontent.com/5876231/41188698-bd85e81a-6beb-11e8-945b-2701832f4994.png)

**Comment by cuonghuynh** [comment]
![2018-06-13_01-03-17](https://user-images.githubusercontent.com/3349033/41308279-af1455e8-6ea5-11e8-98d9-7ed0c35c518f.png)
@bbvothuy e da update code, chi co the test tren digenso.com

**Comment by bbvothuy** [comment]
Thêm 
- Description_en hiển thị tiếng Anh 
- Hình feature product 
![image](https://user-images.githubusercontent.com/5876231/41344382-2fe58004-6f2b-11e8-9c9c-98bf36431975.png)

@cuonghuynh bổ sung thêm nha e
