### ISSUE TITLE
Auto-select filters

### ISSUE THREAD

**Issue by cuonghuynh** [bbvothuy/oemasia#70]
if kva is less than 800
- Genset type: Assembler
- Canopy: Silent
- Delivery Time: <60

Else

- Genset type: Assembler
- Canopy: Open
- Delivery Time: <90

Origin G7: Engine and Alternator are same
Engine Marker -> Auto select Engine Origin

Genset Type: only show
- Import 
- Assembler (search both Finished & CKD)

Hide 
- Frequency
- Phase

TODO:

- [x] Auto select Genset type, Canopy, Delivery Time when change Power
- [x] Update Genset Type filter list to only Import and Assembler
- [x] Hide Frequency, Phase
- [x] For Origin G7, Engine select G7 then auto select Alternator Origin to G7
- [ ] Auto select corresponding Engine Origin to Engine Marker

**Comment by bbvothuy** [comment]
Default 50 Hz and 3 phase
@cuonghuynh
